version: "3"
## note: change to postgres if re-building with docker
services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
